spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://127.0.0.1:5432/db_name}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123456}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update